title: mzfr's Blog
description: "World is my CTF"
author:
  name: "mzfr"
  email: "mehtab.zafar98@gmail.com"
  url: "https://mzfr.github.io"

google_analytics: UA-147356794-1

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "mzfr"
