baseURL: "https://blog.mzfr.me"
title: "mzfr's blog"
theme: "hugo-PaperMod"
paginate: 5


minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: categories
  tag: tags

menu:
    main:
      - name: Home
        url: /
        weight: 1
      - name: Notes
        url: https://wiki.mzfr.me
      - name: Writeups
        url: /ctf/
      - name: About
        url: /about/

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: doom-one

params:
  env: production
  ShowReadingTime: true
  ShowPostNavLinks: true
  assets:


  homeInfoParams:
    enabled: True
    Title: "$ whoami"
    Content: "Mehtab Zafar: Mutating one day at a time, with an unknown time budget"

  socialIcons:
    - name: github
      url: "https://github.com/mzfr"
    - name: email
      url: "mailto:hello@mzfr.me"
    - name: rss
      url: "https://blog.mzfr.me/index.xml"
    - name: resume
      url: "https://github.com/mzfr/resume/blob/master/Mehtab_Zafar_resume.pdf"
