baseURL: "https://blog.mzfr.me"
title: "~/mzfr"
theme: ["PaperMod"]
pagination:
  pageSize: 10

mainSections: ["posts"]

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: categories
  tag: tags

menu:
    main:
      - name: Posts
        url: /posts/
        weight: 1
      - name: Writeups
        url: /ctf/
        weight: 2
      # Books are kept as a draft for later publication.
      # - name: Books
      #   url: /books/
      #   weight: 3
      - name: Notes
        url: https://wiki.mzfr.me
        weight: 4
      - name: Resume
        url: https://github.com/mzfr/resume/blob/master/Mehtab_Zafar_resume.pdf
        weight: 5

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: gruvbox
  goldmark:
    renderer:
      unsafe: true
params:
  env: production
  ShowReadingTime: true
  ShowPostNavLinks: true
  disableThemeToggle: true
  assets:
    disableHLJS: true

  socialIcons:
    - name: github
      url: "https://github.com/mzfr"
    - name: googlescholar
      url: "https://scholar.google.com/citations?hl=en&user=jjZ7jRQAAAAJ"
    - name: email
      url: "mailto:hello@mzfr.me"
    - name: rss
      url: "https://blog.mzfr.me/index.xml"
