baseURL: "https://blog.mzfr.me"
title: "mzfr's Blog"
theme: "hugo-PaperMod"
paginate: 5

googleAnalytics: UA-147356794-1

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: categories
  tag: tags

menu:
    main:
      - name: Home
        url: /
        weight: 1
      #- name: Blog
        #url: posts
        #weight: 2
      - name: Notes
        url: https://wiki.mzfr.me
      - name: Writeups
        url: /CTF/
      - name: About
        url: /about/
    
params:
  env: production
  ShowReadingTime: true

  homeInfoParams:
    enabled: True
    Title: Hi 👋
    Content: "I'm Mehtab Zafar, a developer who spends most of his time doing bug bounties."

  socialIcons:
    - name: twitter
      url: "https://twitter.com/0xmzfr"
    - name: github
      url: "https://github.com/mzfr"
    - name: email
      url: "mailto:hello@mzfr.me"
    - name: buymeacoffee
      url: "https://github.com/sponsors/mzfr"
